# Generated by Django 4.0.2 on 2022-05-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_finished',
            new_name='isfinished',
        ),
    ]
